

server:
    port: 8082

spring:
  application:
    name: service-hi

  redis:
    port: 6379
    host: 127.0.0.1

  datasource:
    url: jdbc:mysql://localhost:3306/789?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: update


  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
